jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0        # nodig om te kunnen pushen
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: pip install requests pandas lxml beautifulsoup4 html5lib

      - name: Build cache JSON
        env:
          TMDB_API_KEY: ${{ secrets.TMDB_API_KEY }}
        run: python .github/scripts/build_cache.py

      - name: Commit & push caches
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git pull --rebase
          git add cache/netflix_nl_series.json cache/netflix_nl_movies.json
          git diff --staged --quiet && echo "No changes" || git commit -m "Update Netflix NL caches"
          git push
