name: Build Netflix NL Top 10 cache

on:
  schedule:
    - cron: "0 6 * * *"   # dagelijks om 06:00 UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: pip install requests pandas

      - name: Build cache JSON
        env:
          TMDB_API_KEY: ${{ secrets.TMDB_API_KEY }}
        run: python .github/scripts/build_cache.py

      - name: Commit & push if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add cache/netflix_nl_series.json
          git diff --quiet && echo "No changes" || git commit -m "Update Netflix NL cache"
          git push

